config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      put 'toggle'
    end
  end
  root 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  def closed?
    not closed_at.nil?
  end

  def self.open_tasks
    where(closed_at: nil).count('id')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :toggle]

  def index
    @tasks = Task.all
    @task  = Task.new
    @open_tasks = Task.open_tasks
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.save
    @open_tasks = Task.open_tasks
  end

  def destroy
    @task.destroy
    @open_tasks = Task.open_tasks
  end

  def toggle
    @task.closed_at = @task.closed? ? nil : Time.now
    @task.save
    @open_tasks = Task.open_tasks
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:what)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :what %><br>
    <%= f.text_field :what %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li id="task-<%= task.id %>" class="all <%= task.closed? ? 'completed' : 'active' %>">
  <%= link_to toggle_task_path(task), remote: true, method: :put do %>
    <input class="toggle" type="checkbox" <%= 'checked' if task.closed? %>>
  <% end %>
  <label data-ember-action="449"><%= task.what %></label>
  <%= link_to task, remote: true, method: :delete do %>
    <button class="destroy"></button>
  <% end %>
</li>

app/views/tasks/create.js.erb
$('#todo-list').append('<%= escape_javascript(render partial: 'task', locals: {task: @task}) %>');
$('#task_what').val('');
$('#todo-count strong').text('<%= @open_tasks %>');

app/views/tasks/destroy.js.erb
$('#task-<%= @task.id%>').remove();
$('#todo-count').val('<%= @open_tasks %>');
$('#todo-count strong').text("<%= pluralize(@open_tasks, 'item') %>");

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<section id="todoapp">
  <header id="header">
    <h1>todos</h1>
    <%= form_for @task, remote: true do |f| %>
      <%= f.text_field :what, placeholder: "What needs to be done?" %>
    <% end %>
  </header>
  <section id="main">
    <input id="toggle-all" class="" type="checkbox">
    <ul id="todo-list">
      <%= render @tasks %>
    </ul>
  </section>
  <footer id="footer">
    <span id="todo-count"><strong><%= pluralize(@open_tasks, 'item') %></strong> left</span>
    <ul id="filters">
      <li>
        <a class="selected" data-filter="all">All</a>
      </li>
      <li>
        <a class="" data-filter="active">Active</a>
      </li>
      <li>
        <a class="" data-filter="completed">Completed</a>
      </li>
    </ul>
  </footer>
</section>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>What:</strong>
  <%= @task.what %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/toggle.js.erb
<% if @task.closed? %>
  $('#task-<%= @task.id%>').addClass('completed').removeClass('active');
  $('#task-<%= @task.id%> .toggle').prop('checked', true);
<% else %>
  $('#task-<%= @task.id%>').removeClass('completed').addClass('active');
  $('#task-<%= @task.id%> .toggle').prop('checked', false);
<% end %>

$('#todo-count strong').text("<%= pluralize(@open_tasks, 'item') %>");